### ISSUE TITLE
使用KDF生成的token与原token始终不匹配

### ISSUE THREAD

**Issue by lyf0409** [yananli117/E2SE#1]
您好，想问下您用户登录时拿存储的sid，passphrase生成的token与注册时生成的token不一样，都是用KDF函数生成，参数都是一样，但是token就是不一样，那如何进行token匹配验证登录密钥服务器呢？

**Comment by yananli117** [comment]
KDF是deterministic function,两次输入相同，KDF函数输出应该是一样的。
你是用自己写的代码吗？有没有可能是encode的方式不同导致两次KDF的输入不一样呢？用同一个输入run两次应该输出是一样的吧

**Comment by yananli117** [comment]
> 您好，想问下您用户登录时拿存储的sid，passphrase生成的token与注册时生成的token不一样，都是用KDF函数生成，参数都是一样，但是token就是不一样，那如何进行token匹配验证登录密钥服务器呢？



> 您好，想问下您用户登录时拿存储的sid，passphrase生成的token与注册时生成的token不一样，都是用KDF函数生成，参数都是一样，但是token就是不一样，那如何进行token匹配验证登录密钥服务器呢？

KDF是deterministic function,两次输入相同，KDF函数输出应该是一样的。
你是用自己写的代码吗？有没有可能是encode的方式不同导致两次KDF的输入不一样呢？用同一个输入run两次应该输出是一样的吧

**Comment by lyf0409** [comment]
您好，是不一样的，我参照您的代码实现的是省去通信过程的流程，想问问您是什么原因，导致kdf值不一样呢
![image](https://user-images.githubusercontent.com/93577125/227722395-00ebe081-feec-4bce-be16-25365286518f.png)

<img width="223" alt="59d118a9c3049c3bbf7ca53c12b5e58" src="https://user-images.githubusercontent.com/93577125/227722343-ce4370e1-b73d-4999-8aea-fdc44a80532d.png">

**Comment by yananli117** [comment]
> 您好，是不一样的，我参照您的代码实现的是省去通信过程的流程，想问问您是什么原因，导致kdf值不一样呢 ![image](https://user-images.githubusercontent.com/93577125/227722395-00ebe081-feec-4bce-be16-25365286518f.png)
> 
> <img alt="59d118a9c3049c3bbf7ca53c12b5e58" width="223" src="https://user-images.githubusercontent.com/93577125/227722343-ce4370e1-b73d-4999-8aea-fdc44a80532d.png">

你打印bytes array用的方法不对，”[B@... “这个好像是地址，你可以用Arrays.toString()试一下，我找了一个参考https://www.geeksforgeeks.org/arrays-tostring-in-java-with-examples/，或者你自己搜一下使用方法

**Comment by lyf0409** [comment]
还想问问您在验证tao的时候，是密钥服务器将之前客户端生成ivct发给客户端，得到tao=KDF(ivct,k2)与tao_take(存在密钥服务器上的tao)进行匹配吗？

**Comment by lyf0409** [comment]
感谢作者！已经得到解决。
![image](https://user-images.githubusercontent.com/93577125/227723977-2c8d981f-95f4-4716-beb7-3e9b3d99a98b.png)

**Comment by yananli117** [comment]
> 还想问问您在验证tao的时候，是密钥服务器将之前客户端生成ivct发给客户端，得到tao=KDF(ivct,k2)与tao_take(存在密钥服务器上的tao)进行匹配吗？

tao是为了实现完整性的检验，避免rid被恶意修改。检验步骤是你说的那样：服务器根据ivct计算tao，和返回的tao比对是否一致。
建议参考论文中的具体协议https://www.usenix.org/system/files/sec22-chen-long.pdf
谢谢

**Comment by lyf0409** [comment]
还想问问您为什么是tao=KDF（ivct，k2）,而不是tao=KDF（ct，k2）呢？如果是第一种方式，密钥服务器是发ivct还是iv和ct？呢？

**Comment by yananli117** [comment]
Ivct是完整的密文，即iv串联ct，这里的ivct在论文里面用ct表示

**Comment by lyf0409** [comment]
作者您好，还是不太理解客户端是如何得到解密后的密钥的。密钥服务器给客户服务器发送ivct,然后直接执行图2的代码得到解密后的密钥吗？
![image](https://user-images.githubusercontent.com/93577125/227770907-00f28d5f-352d-438f-a039-4a9fd880348b.png)
![image](https://user-images.githubusercontent.com/93577125/227771012-31858552-b32e-40da-849b-36a1646ec081.png)

**Comment by lyf0409** [comment]
我按上述理解进行了尝试，实现代码如图1，运行结果如图2，看到解密后的密钥和原来的密钥不一致，麻烦您看看是什么原因
![image](https://user-images.githubusercontent.com/93577125/227771176-7ce7a04f-4020-4381-89fc-93175835e247.png)
![image](https://user-images.githubusercontent.com/93577125/227771188-4be62457-9d20-4e30-91cf-fbb7dcf42840.png)

**Comment by lyf0409** [comment]
非常非常感谢您的帮助，使得我顺利完成编程得到解密后的密钥！希望日后也能成为像您一样优秀的人！

**Comment by yananli117** [comment]
> 非常非常感谢您的帮助，使得我顺利完成编程得到解密后的密钥！希望日后也能成为像您一样优秀的人！

np, 加油！欢迎深入探讨，我们共同进步！
